### ISSUE TITLE
Relationship to ActiveModel::Atributes

### ISSUE THREAD

**Issue by jaredbeck** [Azdaroth/active_model_attributes#12]
It seems that in 2017 [the Attributes API was implemented in ActiveModel](https://github.com/rails/rails/pull/30985).

Should we add something to the readme here explaining when to use this gem, vs. `ActiveModel::Atributes`?

**Comment by bensheldon** [comment]
I wanted to document here because every few months I remember I have this question and have been a longtime user and copy-paster-into-new-projects of this `active_model_attributes` gem.

It seems like it's possible to use `ActiveModel::Attributes` directly. E.g. this works for me without usage of this gem:

```ruby
class Person 
  include ActiveModel::Model # necessary to initialize with values e.g. `Person.new(name: "Alice")`
  include ActiveModel::Attributes
  
  attribute :name, :string
end

person = Person.new
person.name = 'Alice'
person.name # => Alice
```

Why (now) would I use this gem, vs. `ActiveModel::Attributes`?

**Comment by Azdaroth** [comment]
@bensheldon Now there is not much reason to use it actually if you have a proper version of Rails. This API was not available in ActiveModel for some time, but I think since 5.2 it's been part of Rails already.
